### ISSUE TITLE
Log.ts : duplicated methods with different modifiers.

### ISSUE THREAD

**Issue by azizmatmati** [w3tecch/express-typescript-boilerplate#1]
Hi,
This is a very nice and clean boilerplate !! even if I'm new to typescript, it feels solid enough to build on top of it, but I have question about the reason of the duplication of methods (debug, info, warn, error, log) in `src/core/log/Log.ts` while setting different modifiers for them.

**Comment by hirsch88** [comment]
Hi, thanks for your information. 
We just did a big refactoring, so this issue is gone. Just be patient for our new release.

**Comment by azizmatmati** [comment]
OK ! That sounds promising :) ! I'll wait for it.
Good job ;) !!

**Comment by lucasvinals** [comment]
Hi guys, I'm not sure if this is related but is `winstonLoader` even necessary?
I mean, all logs are handled by the logger in `src/lib/logger/Logger.ts` or I'm missing something? 

Best regards!
