### ISSUE TITLE
Creating resource with make:resource overwrites Targets

### ISSUE THREAD

**Issue by Tyderion** [w3tecch/express-typescript-boilerplate#10]
**OS**: Windows 10
**Version**: newest master (2.0.0-beta.2)

**Description**
When I create a new resource it overwrites the Targets.ts file removing all existing entries and not adding new ones.

**Steps to reproduce**
- `npm run console make:resource`
- Follow wizard, say yes to everything
- At one point it asks `Override "src/undefined"?`

**Result**
It creates a new file 
`File created in: C:\Users\Archie\Documents\Coding\Anime-Loader\crawler-v2\src\constants/Targets.ts`

**Expected**
I expected the script to update the Targets not overwrite them (thus removing the User constants) as well as adding constants for the new resource

**Log**
```text
File created in: <path>\src\database\migrations\20170606114339_create_anime_table.ts
File created in: <path>\src\api\models\Anime.ts
File created in: <path>\src\types\resources\anime.d.ts
File created in: <path>\src\api\repositories\AnimeRepository.ts
File created in: <path>\src\api\services\AnimeService.ts
File created in: <path>\src\api\controllers\AnimeController.ts
File created in: <path>\src\api\requests\AnimeCreateRequest.ts
File created in: <path>\src\api\requests\AnimeUpdateRequest.ts
File created in: <path>\test\black-box\Anime.ts

? Update IoC targets? Yes
? Override "src/undefined"? Yes
File created in: <path>\src\constants/Targets.ts
```

**Comment by Tyderion** [comment]
The problem are the paths (and seperators) don't match between windows / unix ( "/" vs "\")

**Comment by dweber019** [comment]
PR https://github.com/w3tecch/express-typescript-boilerplate/pull/11 has fixed this issue.
