### ISSUE TITLE
Running SQLite3 for testing while using Postgres for development/test/prod

### ISSUE THREAD

**Issue by raime910** [w3tecch/express-typescript-boilerplate#105]
I am using the boilerplate for a personal project that uses Postgres database in dev, test, and prod. I've got it configured where it uses a database first approach and syncs the api/models folder with the tables I have in the database. But when I start running the tests - I get this an error saying;

`DataTypeNotSupportedError: Data type "character varying" in "User.FirstName" is not supported by "sqlite" database.`

Which makes sense because in SQLite "character varying" is not a valid type. Is there a way to get around this? Is this boilerplate strictly for MySQL database use only?

**Comment by hirsch88** [comment]
Hi @raime910 

Well this should be configured in the .env.test file.

Cheers
