### ISSUE TITLE
Nodemon + VS Code Debugger

### ISSUE THREAD

**Issue by konraddysput** [w3tecch/express-typescript-boilerplate#106]
Hi,

Is there any way to provide instruction how to setup nodemon and VS Code debugger together? I try to setup project with Nodemon instructions but it doesnt work as expected. I think information about nodemon support should have much more details.

Thanks.

**Comment by hirsch88** [comment]
Hi @konraddysput 

Unfortunately, I have never done that. I just build the app and debug then, but if you find a solution please share it :-)

thanks

**Comment by konraddysput** [comment]
@hirsch88  still no luck. 

Right now Im building application via terminal and then run VS Code debugger. When I try to build app when Im on debugging mode, In most cases VSCode stop debugging.

**Comment by hirsch88** [comment]
Those changes are now in the version 3.10
