### ISSUE TITLE
Question about swagger.json

### ISSUE THREAD

**Issue by mwiley63** [w3tecch/express-typescript-boilerplate#109]
Hello, is there a way to automatically generate the contents of swagger.json? 

It appears that the models are being auto-generated after running npm setup, is this correct? 

However, I can't seem to automatically generate swagger endpoints for new controllers as they are added to the project.  What would be the best way to add new controllers and routes to the swagger.json file?

**Comment by michalzubkowicz** [comment]
You can add task for swagger generation on build time. 

In package-scripts.js like:

 generateSwagger: {
            script: series(
                runFast('./commands/swaggerconfig.ts'),
            ),
            hiddenFromHelp: true
        },

and then add this task to package.json
