### ISSUE TITLE
Missing env variables should raise exceptions.

### ISSUE THREAD

**Issue by michalzubkowicz** [w3tecch/express-typescript-boilerplate#110]
Currently when some variable is missing we can jump into a strange looking error like "Cannot read property 'length' of undefined". It's hard to debug something like that so better is to raise exception. I can prepare PR with that if will be merged.

**Comment by hirsch88** [comment]
Hi @michalzubkowicz 

A PR would be awesome

Thanks

**Comment by hirsch88** [comment]
This changes are now in the version 3.1.0
