### ISSUE TITLE
How do you get a token?

### ISSUE THREAD

**Issue by jaspergreen** [w3tecch/express-typescript-boilerplate#112]
Could you give an example of how to consume the API?
1. Get token
2. Get list of Users

**Comment by hirsch88** [comment]
Hi @jaspergreen 

Well there is no auth example, because normally I use auth0 services for that

cheers

**Comment by AnastasiusVivaldus** [comment]
@jaspergreen  This repo doesn't come with routes to register/login a user and thereby acquire a JWT token. The `yarn setup` command seeds the DB with usernames and passwords. Each user has the password 1234. Most usernames are randomly generated by [faker](https://www.npmjs.com/package/faker), but the username 'bruce' is always included. To access the list of all users, you need to include the Authorization header with a username and password (as though you were one of the users in the DB), and they have to be base-64 encoded. After setting up and running `yarn start serve`, try the following:

curl -v http://localhost:3000/api/users \
     -H "Authorization:Basic $(echo -n bruce:1234 | base64 )" \
     -H 'Accept:application/json'
  
Note 1: depending on your version of base64, you might need to pipe it through e.g. `tr -d \\n` to remove e.g. a '\n' char that it tacks on to the end.
Note 2: [this repo](https://github.com/w3tecch/express-typescript-boilerplate-example#-006---auth0-integration) looks like it is forked from an earlier version and includes instructions for how to (add JWT tokens, though I havent tried it myself).

@hirsch88 I'm sure others would greatly appreciate some updated documentation on how to add JWT login/registration routes.
