### ISSUE TITLE
how would I use aws-serverless-express

### ISSUE THREAD

**Issue by rynop** [w3tecch/express-typescript-boilerplate#113]
I'd like to use [aws-serverless-express](https://github.com/awslabs/aws-serverless-express) but I can't figure out how I would inject the middleware and omit the listen, since the app and the protocol are [tied together](https://github.com/w3tecch/express-typescript-boilerplate/blob/develop/src/loaders/expressLoader.ts#L38). 

Anyone done this before (cleanly)?

**Comment by hirsch88** [comment]
Hi @rynop 

Create a loader and register your middleware

Cheers
