### ISSUE TITLE
How can swagger.json be regenerated?

### ISSUE THREAD

**Issue by Phrohdoh** [w3tecch/express-typescript-boilerplate#125]
This project is a great example of boilerplate, so thanks for all your hard work on that!

Forgive my ignorance but I am a bit new to nodejs and typescript so I can not figure out what tooling to use to regenerate the Swagger API manifest (say I make API changes and want them reflected in the doc / UI).

Any hints would be much appreciated!

**Comment by hirsch88** [comment]
Hi @Phrohdoh please create a PR and we will have look at it. :-)

**Comment by phrohdoh** [comment]
@hirsch88 I'm asking how to do this and you're asking me to file a PR doing this? Doesn't really make sense to me. :)

**Comment by somehowchris** [comment]
A solution could be using or for efficiency reasons rewriting [typescript-rest-swagger](https://www.npmjs.com/package/typescript-rest-swagger) and implementing it in the boilerplate to go along with typeorm and routing-controllers, etc.

Would be amazing to not have to write those swagger files again and again.

**Comment by sscotth** [comment]
How about something like [tsoa](https://github.com/lukeautry/tsoa)

**Comment by gualtierim** [comment]
Hy, i'have done the PR #141 that integrate routing-controllers-openapi in order to solve this problem.

**Comment by gualtierim** [comment]
> How about something like [tsoa](https://github.com/lukeautry/tsoa)

In the PR #141 I chose `routing-controllers-openapi` because the boilerplate use `routing-controllers` to create the expressApp and this library use the metadatas created during the factory process. I used also `class-validator-jsonschema` to create schemas with validators declared with `class-validator`. In my opinion `tsoa` would make a breaking not necessary.

**Comment by somehowchris** [comment]
#141 ?

**Comment by epiphone** [comment]
Seems like #141 got a bit stalled so I had a go in #175. Any chance of getting it reviewed @hirsch88? Thanks!

**Comment by phrohdoh** [comment]
#175 appears to have addressed this, so I'm closing the issue.
