### ISSUE TITLE
unfinished compile

### ISSUE THREAD

**Issue by somehowchris** [w3tecch/express-typescript-boilerplate#126]
When running `yarn start build` or `npm run build `everything seems to be ok. Afterwards running `yarn start` it doesn't seem to find dist/app.js because there is none and therefore `node dist/app.js` doesn't work.

`
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
The script called "start" which runs "cross-env NODE_ENV=production node dist/app.js" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "default" which runs "nps start" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TelcoCloudPortalBackend@1.0.0 start: `nps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TelcoCloudPortalBackend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by efukela** [comment]
that's cause the dist file are are dist/src/app js not dist/app.js

**Comment by somehowchris** [comment]
then please change those start scripts

**Comment by efukela** [comment]
You can always submit PR.

**Comment by somehowchris** [comment]
> that's cause the dist file are are dist/src/app js not dist/app.js

workarounds aren't meant for production

**Comment by hirsch88** [comment]
Fixed that issue and is now solved in the version 3.1.0
