### ISSUE TITLE
How to run console commands on test?

### ISSUE THREAD

**Issue by jasonvillalon** [w3tecch/express-typescript-boilerplate#13]
Hi,

Is there a way to run console command on test beforeAll. like db:reset and db:seed

Best Regards

**Comment by jasonvillalon** [comment]
ahh i got it. nvm

**Comment by clabnet** [comment]
Sorry, can you explain how to ?

**Comment by jasonvillalon** [comment]
import { DatabaseResetCommand } from '../../src/console/DatabaseResetCommand';

...

beforeAll(async () => {
        const command = new DatabaseResetCommand();
        await command.run();

**Comment by clabnet** [comment]
Many thank's, bye


Il 19/10/2017 16:57, Jason Villalon ha scritto:
