### ISSUE TITLE
Clean build for production

### ISSUE THREAD

**Issue by somehowchris** [w3tecch/express-typescript-boilerplate#130]
Thanks for fixing some things for prod. I would love to see a clean, standalone prod build.

Let me explain.

For efficiency reasons we only upload the dist folder. Which usually is standalone and can be executed without a problem. For example vue stuff is built and can be served without some other things. In the compiled world we get a standalone app or something to execute.
My experience so far we have to copy and change some things to get this working with this boilerplate. Not just for us but generally logically it would make sense make app.js or some data executable by node and have everything (package.json, etc.) included (not .env, for those which dont know in prod envs shouldn't be served by a file).

Would love to see this happening and easing some pain off of going to production.
Appreciate your work.

**Comment by hirsch88** [comment]
Hi @somehowchris ,
Please create a PR and we will have a look at it.
Thanks
