### ISSUE TITLE
Can't install due to broken dependency

### ISSUE THREAD

**Issue by enyineer** [w3tecch/express-typescript-boilerplate#135]
One of the dependencies from this boilerplate seems to use event-stream@3.3.6 which had a backdoor added by an attacker (See: https://github.com/dominictarr/event-stream/issues/116 )
The boilerplate can't be installed because this version got deleted from yarn and npm.

**Comment by Paul75** [comment]
Hello,

Sorry for me also yarn or npm can install packages .... nothing wrong ...

Thanks

**Comment by wilson-adap** [comment]
Error: 
> error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by enyineer** [comment]
@wilson-adap that exact same error also pops up for me.

**Comment by KrisTemmerman** [comment]
Event stream has found with malicious code [source](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream) .

**Comment by KrisTemmerman** [comment]
Looked into it and raised a  PRQ https://github.com/w3tecch/express-typescript-boilerplate/pull/137

**Comment by imanabu** [comment]
Adding the following in package.json has fixed it for me,

 "resolutions": {
    "**/event-stream": "^4.0.1"
  },
