### ISSUE TITLE
Validate doesnt remove the field that doesnt exists in request schema

### ISSUE THREAD

**Issue by jasonvillalon** [w3tecch/express-typescript-boilerplate#14]
Hi,

Is there a way to clean the request body when validating?

**Comment by hirsch88** [comment]
Hi,
This would be a nice feature.
Feel free to create a pull-request. We would be happy to review and integrate it.

**Comment by jasonvillalon** [comment]
i changed 

from 
`const keys = Object.keys(input);`
to
`const keys = Object.keys(this);`

in core/api/RequestBody.ts

so request body will be filtered if not in schema
