### ISSUE TITLE
How does the auth works?

### ISSUE THREAD

**Issue by humbertowoody** [w3tecch/express-typescript-boilerplate#145]
I am using this boilerplate as it fits mostly my current project's requirements. Everything is understandable, except for the Auth part. Maybe a section in the README? Or on the Wiki some other issue talks about? A little guidance about how auth is performed on the boilerplate _out of the box_ will be really helpful :)

**Comment by chmieleski** [comment]
What you haven't understood?
I can try to help you.

**Comment by chmieleski** [comment]
I mean, it is simple to understand how auth works.
You may check the file AuthService.ts

**Comment by humbertowoody** [comment]
Maybe just an explanation of how it works? I can’t seem to understand how to integrate with the mock server README.md makes reference. Is it a `Bearer` token?

**Comment by chmieleski** [comment]
It use  Basic Auth, it's user + password separated by ':' and encoded using base64.

**Comment by chmieleski** [comment]
``` javascript
public parseBasicAuthFromRequest(req: express.Request): { username: string, password: string } {
  const authorization = req.header('authorization');
  if (authorization && authorization.split(' ')[0] === 'Basic') {
    this.log.info('Credentials provided by the client');
      const decodedBase64 = Buffer.from(authorization.split(' ')[1], 'base64').toString('ascii');
      const username = decodedBase64.split(':')[0];
      const password = decodedBase64.split(':')[1];
      if (username && password) {
        return { username, password };
      }
   }
}
```

**Comment by humbertowoody** [comment]
Now I get it! So the mock server is not necessary, right? Also, to integrate multiple auth systems, say one _Team_ route needs JWT and _User_ needs a Basic Auth, should it be on 2 files, or in the same file?  Thank you very much for the information :)

EDIT: To be clear, how do you integrate 2 auth systems?

**Comment by humbertowoody** [comment]
I am closing this since it isn't really an issue, perhaps adding the information in the README about it will make it clearer for newcomers :)
