### ISSUE TITLE
Question about EntityManager vs Repository 

### ISSUE THREAD

**Issue by lixaotec** [w3tecch/express-typescript-boilerplate#152]
Dear folks,

Whats behind the decision of using typeorm Repository instead EntityManager for the architecture?

I´d be glad if you can share you comments on that decision or best practices.

What about transactions, how should I work. 

I would appreciate very much if you can also share resources on this archtecture model concepts

Thank you

**Comment by morishjs** [comment]
@lixaotec 

The time has been passed after a question. But I would like to share a [link](https://stackoverflow.com/questions/14621495/what-is-the-difference-between-an-spring-entity-manager-and-spring-data-reposito) to make you much clear as well as me. 

About 'repository', you can find a concept in the [book](https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215)

**Comment by lixaotec** [comment]
Thank you.

Repository is the pattern to use.

Ive been reading more about ddd, and microservices architecture.

I miss some boiler for that in this project. Uow, message queue for commands and queries.
