### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "^7.7.3.

### ISSUE THREAD

**Issue by peralmq** [w3tecch/express-typescript-boilerplate#19]
Thanks for a super nice and thorough boilerplate, loving the file structure you use! :)

Any reason why you have `"engine": {"node": "^7.7.3"}` in `package.json`? It breaks `npm run setup` when using Node.js v8.5. I removed that line from `package.json` and then the setup is working. So seems like an unnecessary "safety" check to lock down the node version, no?

This is the error I got while keeping those lines in `package.json` if anyone searches for this.
```
npm run setup
...
error express-typescript-boilerplate@2.0.0-beta.2: The engine "node" is incompatible with this module. Expected version "^7.7.3".
...
```

**Comment by CharnjeetIotasol** [comment]
I am facing same issue. Have you find any solution for this.

**Comment by CharnjeetIotasol** [comment]
I have found the solution:

choco uninstall nodejs
choco install nodejs.install --version 7.7.3 

Run npm run setup. 

Now Issue will be resolved.

**Comment by peralmq** [comment]
> I am facing same issue. Have you find any solution for this.

Yes, remove the `"engine"` field from `package.json`

**Comment by CharnjeetIotasol** [comment]
@peralmq I am not able to see new Resource I have created I am getting 404. Can you help me is I am miss to add some where ?

**Comment by hirsch88** [comment]
https://github.com/w3tecch/express-typescript-boilerplate/releases/tag/2.0.0-beta.3
