### ISSUE TITLE
Plugin 'inversify-express-utils' error

### ISSUE THREAD

**Issue by lubej** [w3tecch/express-typescript-boilerplate#2]
I have an issue with running the build on Windows 10.

I get the following error : error: [core:Bootstrap] No matching bindings found for serviceIdentifier: Symbol(Controller), when running "npm start". I tried it on versions 2.0.0-beta and 1.7.0.

If I comment this line inversifyExpressServer.build() in Bootstrap.ts, then i can run it. But it doesn't hit the users controller.

npm --version: 5.0.4
node --version: v6.11.0
yarn --version: 0.27.5

Is this a known issue, or is it just me?

**Comment by dweber019** [comment]
I'll have a look into this shortly.

**Comment by lubej** [comment]
UPDATE.
I just tried running with Bash for windows and it works perfectly.
I will investigate further...

**Comment by dweber019** [comment]
@lubej I have pushed a branch (feature/fix-windows-issues) with some windows fixes.
There are a few things left to check but the core works:
[] tests (there's a bug in jest https://github.com/facebook/jest/issues/2807)
[] the console commands
[] retest on unix systems

**Comment by lubej** [comment]
@dweber019 just tried it. Works fine.
Thanks for quick response.
