### ISSUE TITLE
Unable to Get New Resouce in Swagger and Rest Client

### ISSUE THREAD

**Issue by CharnjeetIotasol** [w3tecch/express-typescript-boilerplate#20]
Hi 

I have created on Resource Product and I have got the all file which is container but after that I have run the npm run serve. command but still my apis is un-access able. It returning 404. Swagger also does not update for that tables.

I have add the following entry after resource file:

a) Targets.ts add Model, Controller,etc.
b) Tables.ts.

Can any one help me how to access new created Resource  ?

**Comment by hirsch88** [comment]
Hi,
We do not have a script that updates the swagger. However, I just created a new resource with `npm run console make:resource` and it worked.
Did you tell the console to update the IoC?

**Comment by CharnjeetIotasol** [comment]
Hi 

Yes, I have added on resource with this npm run console make:resource. But swagger does not updated.

**Comment by hirsch88** [comment]
Yes, we are aware of that. You have to manage the swagger by your own
