### ISSUE TITLE
How to Pass Role to authenticate.use in Controller

### ISSUE THREAD

**Issue by CharnjeetIotasol** [w3tecch/express-typescript-boilerplate#22]
Hello,

I have one question regarding the role. Can you please help me how to add Role based authenticate to api in controller. I want to pass the Role to AuthenticateMiddleware#use function.

**Comment by hirsch88** [comment]
Hi,

The AuthenticateMiddleware is not supposed to check roles.

Try to create a new middleware for roles and add them as hooks in the controller.
