### ISSUE TITLE
QUESTION: How to use a different database instance for black-box tests?

### ISSUE THREAD

**Issue by slavkomae** [w3tecch/express-typescript-boilerplate#25]
What's the most elegant way to do this? I'm fairly new to typescript (I know how to use DI to do this in C# or Java), so I'm just wondering what the least painful path to achieve this is. Thanks in advance.

**Comment by hirsch88** [comment]
Hi,

I guess a good approach would be to create a config for the test and there you can set witch middlewares or databases.
