### ISSUE TITLE
VSCode debug task doesn't work

### ISSUE THREAD

**Issue by Neku** [w3tecch/express-typescript-boilerplate#4]
When I try to run it I get ``` Attribute 'program' does not exist ('/Users/simone/Documents/workspace/express-typescript-boilerplate/src/app.js.js'). ```

Changing the path of program from src/ to dist/ seems to fix it

**Comment by hirsch88** [comment]
This issue is already fixed in the develop branch and will be released with the next beta version shortly.

**Comment by hirsch88** [comment]
https://github.com/w3tecch/express-typescript-boilerplate/releases/tag/2.0.0-beta.1
