### ISSUE TITLE
Can't run npm start setup

### ISSUE THREAD

**Issue by ontoport** [w3tecch/express-typescript-boilerplate#43]
I'm on Lubuntu 17.04 running on an virtualbox latest release. Following your readme, I first created a new database on the local mysql server and entered its name and the credentials in .env. When issuing 'npm start setup' I get the following error messages (this is the content of the generated logfile):
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', 'setup' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle express-typescript-boilerplate@3.0.0-beta.2~prestart: express-typescript-boilerplate@3.0.0-beta.2
6 info lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: express-typescript-boilerplate@3.0.0-beta.2
7 verbose lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/nn/Projects/Examples/express-typescript-boilerplate/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: CWD: /home/nn/Projects/Examples/express-typescript-boilerplate
10 silly lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: Args: [ '-c', 'nps "setup"' ]
11 silly lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: Returned: code: 1  signal: null
12 info lifecycle express-typescript-boilerplate@3.0.0-beta.2~start: Failed to exec start script
13 verbose stack Error: express-typescript-boilerplate@3.0.0-beta.2 start: `nps "setup"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid express-typescript-boilerplate@3.0.0-beta.2
15 verbose cwd /home/nn/Projects/Examples/express-typescript-boilerplate
16 verbose Linux 4.10.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "setup"
18 verbose node v8.9.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error express-typescript-boilerplate@3.0.0-beta.2 start: `nps "setup"`
22 error Exit status 1
23 error Failed at the express-typescript-boilerplate@3.0.0-beta.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

>>> Question: What did I overlook? What would I have to do differently?

Cheers, Wolfram

**Comment by dweber019** [comment]
@ontoport did you run `yarn install` first?
We have a logical bug there, as we are using nps before the dependencies have been installed the `setup` command fails.

**Comment by ontoport** [comment]
Thank you! Just revisited the project. Works fine. Proposal: please include the Swagger User and PW in the README.md. I finally found it in the .env file. Thanks again.
