### ISSUE TITLE
No more scaffolding?

### ISSUE THREAD

**Issue by jasonvillalon** [w3tecch/express-typescript-boilerplate#47]
Hi,

I just checkout this boilerplate, but npm run console is now not available? did you make separate project for that or it is gone for good?

Best Regards,
Jason Villalon

**Comment by dweber019** [comment]
Hi @jasonvillalon 

With the newest release we have removed the console as it wasn't our top priority to provide the scaffolding functionality. We did a complete refactoring of the boilerplate and added a lot of examples.

Currently we don't plan to bring the feature back as we have other features we like to bring alive.

Cheers
