### ISSUE TITLE
Question: How to assign seeded item to other entity with fix value?

### ISSUE THREAD

**Issue by sandrooco** [w3tecch/express-typescript-boilerplate#49]
Assume the following entities:

```
@Entity()
export class TaskType {
    @PrimaryGeneratedColumn() public id: number;
    ...

    @OneToMany(type => Task, task => task.taskType)
    public tasks: Task[];
}
```
```
@Entity()
export class Task {
    @PrimaryGeneratedColumn() public id: number;
    
    @IsNotEmpty()
    @Column()
    public name: string;

    @ManyToOne(type => TaskType, taskType => taskType.tasks)
    @JoinTable()
    public taskType: TaskType;
}
```

A task can have one of the two following types: 'simple' or 'qualityCheck'. Seeding tasks and taskTypes separately works fine but not with the relation. I tried it with nested factories [as described in the docs](https://github.com/w3tecch/express-typescript-boilerplate#2-create-a-seed-file), this although works only with dynamic values, right?

A `Task` belongs to a `DataCenter` - following seed:
```
await times(10, async (n) => {
    const dc = await factory.get(DataCenter).create();
    dc.tasks = await factory.get(Task).createMany(5);
    dc.areas = await factory.get(Area).createMany(randomNumber(5, 10));
    await em.save(dc);
});
```

**Comment by hirsch88** [comment]
Hi @sandrooco 

First you have to seed the taskType and the you can pass them to the task factory as an argument.

**Comment by dweber019** [comment]
Soon there will be a new release regarding the seeding functionality with better readme description.
