### ISSUE TITLE
Submit the Seed functionality back to the Typeorm project

### ISSUE THREAD

**Issue by am17torres** [w3tecch/express-typescript-boilerplate#56]
The [Typeorm](https://github.com/typeorm/typeorm) project desperately needs the seeding functionality that has been built into this project. 

Have you considered submitting a PR to that project so it can be supported natively by Typeorm?

**Comment by et** [comment]
Just going to add my thoughts on this. Please do contribute back. This project is awesome and clearly ya'll know some intense typescript that could benefit the larger community 😄

**Comment by LogansUA** [comment]
Maybe, at least separate it to some module?
Because, f.e. in production mode seeders don't need at all, so with module we can put them into devDependencies section.

**Comment by LogansUA** [comment]
So... After few weeks, I finally found time separate this functionality. Here's the [repository](https://github.com/LogansUA/typeorm-seed-extension) and [npm package](https://www.npmjs.com/package/typeorm-seed-extension).

REMEMBER: This extension is not finished, I would be glad to receive PR's and Issues from you.

**Comment by hirsch88** [comment]
Finally I move the seeding part to a new repository [typeorm-seeding](https://github.com/w3tecch/typeorm-seeding).

Check out the new version 3.1.0
