### ISSUE TITLE
Swagger : TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Paul75** [w3tecch/express-typescript-boilerplate#58]
Hello,

I test and launch but all script can't works I've got error : TypeError: Failed to fetch

And authentification no works ....

Thanks

**Comment by dweber019** [comment]
@Paul75 please provide reproduction steps and more information on your issue.

**Comment by Paul75** [comment]
Hello,

In ecemple I I go tothe page : 
http://localhost:3000/swagger/#/User/FindAllUsers

When I want to try I got : 
curl -X GET "http://http://localhost:3000/api/v1/users" -H "accept: application/json"

why the "http://http://localhost:3000/api/v1/users" ?

Thanks

**Comment by hirsch88** [comment]
Hi @Paul75
This should be fixed in the new version 3.0.0-rc.2.
Cheers

**Comment by Paul75** [comment]
Why Can I autorize ? all tima have error unauthorized

Also the url that mentioned in .env : AUTH_ROUTE="http://localhost:3333/tokeninfo"
not works ....
