### ISSUE TITLE
Call service or repository in event dispatcher

### ISSUE THREAD

**Issue by jasonvillalon** [w3tecch/express-typescript-boilerplate#61]
Hi,

is it encourage to call database queries in event dispatcher? or is there a better way to do it?

Best Regards,
Jason Villalon

**Comment by dweber019** [comment]
Hi @jasonvillalon 

Generally it's fine to do db calls in the event dispatcher.
Use Case: Gathering data for email which will be dispatched over the event dispatcher.

If you provide your use case, we could give you more help.

**Comment by jasonvillalon** [comment]
Hi @dweber019 thanks for reply.

actually right now im calling database queries in EventSubcriber like this:

```
@On(events.postActions.created)
    public async onPostActionsCreate(postActions: PostActions): Promise<void> {
        try {
            const connection: Connection = Container.get('connection');
            const em = connection.createEntityManager();
            const post: any = await em.findOne<Posts>(Posts, {
                where: {id: postActions.postId},
                relations: ['user'],
            });
            console.log(post);
        } catch (err) {
            console.log('error', err);
        }
    }
```

actually i dont like it, is it possible to call service or repository directly here?

Thanks in advance

**Comment by dweber019** [comment]
@jasonvillalon you could try to use the normal typedi annotation for injecting a service.
´´´
constructor(
	private postService: PostService
) { }
´´´

Never tested but maybe it works as event-dispatch does some things with a container and a meta registry.

**Comment by dweber019** [comment]
@jasonvillalon did it work? If you don't mind I close this issue.
We/you can reopen if needed.

**Comment by jasonvillalon** [comment]
@dweber019 no it didnt work. when im injecting dependencies in subscribers its always undefined.

**Comment by jasonvillalon** [comment]
@dweber019  can we reopen this? i really need this feature now :) my event dispatcher modules are so bloated now.

**Comment by jasonvillalon** [comment]
ok i figure out a way to call service inside event dispatcher. i think this will work for me:

```
const em = connection.createEntityManager();
const myService = new MyService(em.getCustomRepository(MyRepository), log);
```

is this the only way?

**Comment by LogansUA** [comment]
@dweber019 It didn't work for me too. Can you reopen it? It's really must have thing.

**Comment by LogansUA** [comment]
@jasonvillalon Maybe this can help you? Directly getting service from container, instead of building it buy yourself.
![screen shot 2018-09-24 at 12 52 21](https://user-images.githubusercontent.com/7515743/45946167-c0aa9700-bff8-11e8-92f1-88706b5e3043.png)
