### ISSUE TITLE
When I can test swagger ? Were is token ?

### ISSUE THREAD

**Issue by Paul75** [w3tecch/express-typescript-boilerplate#64]
Hello,

When I can test swagger ? all are "Error: Unauthorized" ...

Where can I found the token to test ?

The : 
#
# AUTHORIZATION
#
AUTH_ROUTE="http://localhost:3333/tokeninfo"

in configuration not works (404).

Thanks

**Comment by dweber019** [comment]
@Paul75 the `AUTH_ROUTE="http://localhost:3333/tokeninfo"` is used for authentication checking. This url is provided by a 3td party and not included in this repository.

By 3td party I mean:
- Auth0
- Our test server like stated in the readme ([Auth Mock Server](https://github.com/hirsch88/auth0-mock-server))

We do not implement the authentication by our selfs but you can reference this issue about implementation details: https://github.com/w3tecch/express-typescript-boilerplate/issues/52
