### ISSUE TITLE
Integrate Angular 5 in the boilerplate

### ISSUE THREAD

**Issue by giuseppegargiuolo** [w3tecch/express-typescript-boilerplate#65]

**Comment by dweber019** [comment]
Hi @giuseppegargiuolo 

Sorry but we won't do that as this should be a backend only boilerplate.
But feel free to do whatever you want after cloning.

Here a boilerplate for Aurelia also managed by us: https://github.com/w3tecch/aurelia-typescript-boilerplate

Cheers
