### ISSUE TITLE
How do you manage multiple environments?

### ISSUE THREAD

**Issue by et** [w3tecch/express-typescript-boilerplate#66]
For example, say production has a different database name than development. How would you manage this? Two thoughts come to mind:

Either make `.env.development` and `.env.production` and copy the the correct `.env` file over. Or set environment variables in the production environment that sets `DB_NAME`. However, isn't great since you can't have that in version control.
A third option is to completely drop the custom environment handling and use something like [convict](https://github.com/mozilla/node-convict).

**Comment by dweber019** [comment]
Hi @et 

Yes just setup a `.env` file for your local environment.
You should not have multiple config files on one environment. In addition you should not commit any sensitive data to a repository (e.g. DB user and password).

In my opinion a other party needs to provide configuration. For example if you use cloud services like Cloud Foundry or Heroku (https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js) you will load this configuration from the environment variables and this configuration is provided by the cloud provider.

What we do on Cloud Foundry is to setup a [manifest.yaml](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#env-block) to hold the more static env vars.

And if you have a CI like Travis or Jenkins you would also provide the config over the environment variables.

If you like to add an other environment or change the configuration of an environment you don't have to change the version control. You just have to change the config in the cloud and restart the app.

Thanks for the link to [convict](https://github.com/mozilla/node-convict). Seams like an awesome library perfect for frontend (E.g. Webpack webapp) configuration (as there the configuration has to be loaded on at build/compile time).

**Comment by et** [comment]
Thanks for response. Env vars are the way to go. Totally forgot that dotenv [doesn't overwrite existing env vars](https://github.com/bkeepers/dotenv#why-is-it-not-overriding-existing-env-variables) so that should be a safe path.
Thanks!
