### ISSUE TITLE
RepositoryMock should be returning promises

### ISSUE THREAD

**Issue by et** [w3tecch/express-typescript-boilerplate#67]
All the functionality in [here](https://github.com/w3tecch/express-typescript-boilerplate/blob/018cf878a9814851c2669859992725bc99f6cf57/test/unit/lib/RepositoryMock.ts#L11-L29) should be returning a promise to replicate typeorm better.

**Comment by dweber019** [comment]
@et thanks for your feedback. Your totally right.
Could you provide a PR with this change?

**Comment by et** [comment]
#68 😄

**Comment by dweber019** [comment]
@et Awesome, thanks.
