### ISSUE TITLE
Serving public doesn't work when in prod

### ISSUE THREAD

**Issue by sandrooco** [w3tecch/express-typescript-boilerplate#69]
I can serve the frontend from the `public` folder when running `npm start serve`. I doesn't work though when running it from the prod build/`npm start`.

Is there any additional config to be done?

**Comment by dweber019** [comment]
@sandrooco I tested and it works for me.

I created a `index.html` in the root of `src/public`. After `npm start build` the `index.html` was available under `dist/public` and it worked by accessing `http://localhost:3000/`.

Could you retry or provide more information.

Thanks

**Comment by dweber019** [comment]
Closing

**Comment by sandrooco** [comment]
Sorry for the long response time.
The `.gitignore` file had `src/**/*.js` in it, which lead to the error.

**Comment by dweber019** [comment]
@sandrooco it's fixed in develop. Will be released soon
