### ISSUE TITLE
Cluster?

### ISSUE THREAD

**Issue by mateusz-kolecki** [w3tecch/express-typescript-boilerplate#70]
Hi, how to run app with multiple processes to make use of multicore CPU?

**Comment by dweber019** [comment]
@mateusz-kolecki could you review this PR to see if I got your request right. https://github.com/w3tecch/express-typescript-boilerplate/pull/73

**Comment by mateusz-kolecki** [comment]
@dweber019 Yes, this is what I was thinking about.

I am aware of that, this is naive implementation.
Bootstrap logs are duplicated and there is no handling of dead worker.

**Comment by dweber019** [comment]
@mateusz-kolecki would be nice if you could create a PR or did you consider to use [pm2](http://pm2.keymetrics.io/)?

**Comment by Paul75** [comment]
for me I use pm2....
and change to packages.json and add json fiel config pm2

**Comment by dweber019** [comment]
Close issue as the issue isn't active anymore and pm2 can be used as suggested.
