### ISSUE TITLE
Typechecking as part of the linter

### ISSUE THREAD

**Issue by et** [w3tecch/express-typescript-boilerplate#71]
I was hoping that the `npm start lint` would check typechecking errors, but that appears to be out of the [scope of tslint](https://github.com/palantir/tslint/issues/3399).

Do you have a recommended way to add a compile step to the linter via `tsc --noEmit`?

**Comment by dweber019** [comment]
@et currently both commands `npm start serve` and `npm start build` will check tslint and typescript.

**Comment by et** [comment]
Agreed but that is not what a CI would ever run.
