### ISSUE TITLE
npm production migrate?

### ISSUE THREAD

**Issue by lopezm94** [w3tecch/express-typescript-boilerplate#79]
I have run with an issue recently when pushing code to production. `commands/ormconfig.ts` has `src/env` hardcoded instead of `src/dist`. This presents a "problem" when doing migrations with the built code, would you mind if I add a new command in `package.json`?

P.S Awesome work in the package!

**Comment by et** [comment]
I'm experiencing the same thing. @lopezm94 what did you change this to to fix it?

**Comment by et** [comment]
It feels to me that like the `ormconfig.json` should be eliminated. Right now there's duped information between that and the `env` file.

**Comment by dweber019** [comment]
Currently we only need the `ormconfig.json` because of the TypeORM CLI.

> It feels to me that like the ormconfig.json should be eliminated. Right now there's duped information between that and the env file.

The single truth is `env.ts`, which uses `.env` and is used for `ormconfig.json` generation.

@lopezm94 & @et: Would I make sense if the `ormconfig.json` is copyed to `dist` after a build?

**Comment by et** [comment]
@dweber019 - copying the `ormconfig.json` would work.
If that workflow seems complicated though, typeorm can just pluck environment variables from the `.env` file: https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-environment-variables

**Comment by dweber019** [comment]
@et you're right. Setting the environment variables is the proper way.
Will close this issue.

What we do is deploy the whole project (not only the dist) and therefore it works.

**Comment by et** [comment]
@dweber019 - what would help though for people though is to provide uniformity with the db env variables.
So in the [.env](https://github.com/w3tecch/express-typescript-boilerplate/blob/develop/.env.example#L26-L33) file, they should be renamed to `TYPEORM_` variables.

**Comment by dweber019** [comment]
@et could you have a look at https://github.com/w3tecch/express-typescript-boilerplate/pull/95 and provide some feedback what you think. Thanks
