### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by gonza-lito** [w3tecch/express-typescript-boilerplate#82]
Hi is mongo supported? I see typeorm supports it but apparently there are some issues with migrations, when I try to run them I get: "Check schema queries are not supported by MongoDB driver."

**Comment by hirsch88** [comment]
Hi @gonza-lito , we do not support mongo. However, please create pr and we would love to merge it.
Cheers hirsch88

**Comment by dweber019** [comment]
@gonza-lito as we use https://github.com/typeorm/typeorm you can check the support there.

I think this link will help you http://typeorm.io/#/mongodb
