### ISSUE TITLE
Question how can i use pm2 for deployment, what script should i place in ecosystem file?

### ISSUE THREAD

**Issue by AhmedMasoodSiddiqui** [w3tecch/express-typescript-boilerplate#83]
#80 hi, which script should i use if i want to deploy this on a remote server?
`module.exports = {
  apps : [
    {
      name      : 'name of applicaton',
      script    : '**what should i place here**',
      env: {
        COMMON_VARIABLE: 'true'
      },
      env_production : {
        NODE_ENV: 'production'
      }
    }
  ],`

**Comment by dweber019** [comment]
@AhmedMasoodSiddiqui you mean how to start or to build?

**Comment by AhmedMasoodSiddiqui** [comment]
@dweber019 thanks bro , i found the solution, i built the application using pre setup commands and deployed using app.js script. i hope this is the right way.

**Comment by dweber019** [comment]
@AhmedMasoodSiddiqui awesome. Yes build the app and start with `app.js`. I'll close the issue
