### ISSUE TITLE
Upload files error

### ISSUE THREAD

**Issue by Paul75** [w3tecch/express-typescript-boilerplate#85]
Helllo,

I want to create action on controller to upload files.

I've got an error when upload file : " net::ERR_CONNECTION_RESET"

Did you know this ? I use formidable plugin

Thanks

**Comment by Paul75** [comment]
Not error sorry. I do wrong

**Comment by VikasKad** [comment]
@Paul75  are you able complete file upload functionality ?
If yes can you show some example as I am struggling to do file upload functionality.

**Comment by CharnjeetIotasol** [comment]
Hi

Can you please share the file upload functionality?
