### ISSUE TITLE
Implementing Auth0

### ISSUE THREAD

**Issue by tlays11** [w3tecch/express-typescript-boilerplate#87]
Real useful project. Thanks for making it open. I was trying to figure out how to swap out the mock Auth0 server with a real Auth0 account. Do you have any guides here?

**Comment by dweber019** [comment]
@tlays11 actually you have to replace the implementation of these method https://github.com/w3tecch/express-typescript-boilerplate/blob/develop/src/auth/AuthService.ts#L34 with the following request https://auth0.com/docs/api/authentication#user-profile.

Things to change:
- change the auth route => `env.auth.route`
- send user token as header 

Additionally you have to change this line https://github.com/w3tecch/express-typescript-boilerplate/blob/develop/src/auth/currentUserChecker.ts#L19 to use the auth0 email in the where clause or you extend the user model to have a auth0 id field.

Probably you also like to change https://github.com/w3tecch/express-typescript-boilerplate/blob/develop/src/auth/TokenInfoInterface.ts as you get more information from auth0, but that's up to you ;)
