### ISSUE TITLE
support pagination

### ISSUE THREAD

**Issue by jasonvillalon** [w3tecch/express-typescript-boilerplate#9]
Hi,

how can i integrate pagination?

Thanks

Best Regards

**Comment by hirsch88** [comment]
https://github.com/bookshelf/bookshelf/wiki/Plugin:-Pagination

**Comment by jasonvillalon** [comment]
Hi,

Thank you for your reply.

I managed to implement pagination but i have to edit types/bookshelf to make it work

added in Model class definition
`
static fetchPage<T extends Model<any>>(options: any): BlueBird<Collection<T>>;
`
and Collection class definition
`
pagination: any;
`

so i can use something like this 
```
@Get('/')
    public async findAll( @Response() res: myExpress.Response, @RequestHeaders() headers: {
        range: string;
    }): Promise<any> {
        const range = headers.range.split('-');
        const [page, pageSize] = range;
        const users = await this.userService.findAll({
            page,
            pageSize
        });
        return res.found({
            pagination: users.pagination,
            result: users.toJSON()
        });
    }
```

can you share your solution?

Best Regards

**Comment by hirsch88** [comment]
Unfortunately, we do not have a example for pagination yet.
However, we will add this to our to-do list.

**Comment by jasonvillalon** [comment]
that would be great! im going to stick to my work around for now i guess 👍 thanks
