### ISSUE TITLE
not works in last version of TypeOrm and typedi

### ISSUE THREAD

**Issue by Paul75** [w3tecch/express-typescript-boilerplate#90]
Hello,

If I update TypeOrm to 2.1.0 and typedi to 0.7.2 and start project I've got : 

```
src/auth/AuthService.ts:15
        @Require('request') r: any,
         ^
TypeError: typedi_1.Require is not a function
```

Thanks

**Comment by dweber019** [comment]
@Paul75 This pull request will fix it https://github.com/w3tecch/express-typescript-boilerplate/pull/91
