### ISSUE TITLE
Authorize in http://localhost:3000/swagger

### ISSUE THREAD

**Issue by zetekla** [w3tecch/express-typescript-boilerplate#92]
How do I login so I can test/perform and verify all the REST endpoints?

What Value to enter in the form?

**Comment by dweber019** [comment]
Hi @zetekla 

First setup this repository with `npm run setup`

Then use this repo https://github.com/hirsch88/auth0-mock-server and get a token with https://github.com/hirsch88/auth0-mock-server#get-tokenusername for a user in the database (email).

Afterwards go to swagger and test.

**Comment by zetekla** [comment]
I have auth0-mock-server up and running.
So, for the Value input in Swagger form, should I enter the Token I grabbed from auth0-mock-server ? 
How validation should work? I can't seem to get it to work.

Do I keep it http://localhost:3333/tokeninfo ?

**Comment by dweber019** [comment]
Yes the token has to be entered in Swagger right upper corner (Authorize) and there you enter "Bearer <your-token>".

The validation is done in https://github.com/w3tecch/express-typescript-boilerplate/blob/develop/src/auth/authorizationChecker.ts

Yes the auth0-mock-server has to be running and you need to keep AUTH_ROUTE.

Yes it should be the email address of the boilerplate. If you use the vanilla boilerplate then you can do `bruce.wayne@wayne-enterprises.com`.
