### ISSUE TITLE
[question] Using sub directories of models with typeorm and .env config

### ISSUE THREAD

**Issue by mwiley63** [w3tecch/express-typescript-boilerplate#93]
Hello,

What would be the recommended way to add sub directories to the models folder?  When I do the following I get an error with typeorm (as the generated ormconfig.json does not include all the sub directories by default):
```
  models/
     User.ts
     user-details/
        UserRole.ts
```

If I include a type from UserRole.ts into User.ts, I get an error, "Entity Metadata not found".  After looking at the ormconfig.json, I can see that the user-details sub directory is not included into the entities array.

As a hack I hard-coded each entity directory into the ormconfgi.ts command file.  Is there a better way to do this?

Thank you!

**Comment by mwiley63** [comment]
Hi @dweber019 

That worked!  Can't believe I missed the env.ts file 👍 

Thanks!

**Comment by dweber019** [comment]
https://github.com/w3tecch/express-typescript-boilerplate/pull/94 fixes this.
