### ISSUE TITLE
docker error in launch

### ISSUE THREAD

**Issue by Paul75** [w3tecch/express-typescript-boilerplate#97]
Hello,

When I do : 

> docker build -t projet-server .

 I've got : 
```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

Thanks

**Comment by DaNautilus** [comment]
Hey @Paul75 

It seems that you installed an old version (1.0.4) of "upath" node module, which only supports node engines >=4 and <=9.
There's a new version (1.1.0) of "upath" available which supports node engines >=4.
An update of "upath" node module should solve your issue.

https://github.com/anodynos/upath

Greets
