### ISSUE TITLE
Locale Decorator

### ISSUE THREAD

**Issue by Nokama14** [w3tecch/express-typescript-boilerplate#99]
Hello devs
In a project I'm working on I have written a decorator that reads the language settings of the users browser out of a request so we can return properly localized results. My team suggested I should ask you whether you want to include it into your boilerplate. Are you interested / is there a need for this?

**Comment by Nokama14** [comment]
With the decorator it is defineable what languages your application supports. We added a LocaleEnum where the supported languages are written down and then it uses the `accept-languages` header to check which of these languages is the most preferable. If none fit, it is set to english by default.
[LocaleDecorator.zip](https://github.com/w3tecch/express-typescript-boilerplate/files/2030857/LocaleDecorator.zip)

**Comment by lucasvinals** [comment]
Hi guys, how can I incorporate this kind of decorators to a request in a controller? 

Thanks!
